### ISSUE TITLE
How did you extract only hand from mesh ( full human mesh ) 

### ISSUE THREAD

**Issue by rohitdavas** [kaiidams/FreeHand-Dataset#5]
Hi, 
I am kind of working on similar project. I need to figure out how to cut out only hand from mesh. 

Since you have already done so, could you describe the process in blender ? 

Thanks,

**Comment by kaiidams** [comment]
Hi,
The original bones and meshes are from MakeHuman. I exported the model into .blend file and then removed unneeded bones and meshes by Blender. If you haven't used Blender before, this might be a bit difficult to do. You can select an object with left click and then press TAB to enter the edit mode, then select an item and press 'X' key to delete it.

**Comment by rohitdavas** [comment]
Thanks. 

I am doing the same. I deleted the unneeded bones. But since the hand and body are same mesh, unable to separate them. 

1. I tried to select the vertices on hand and create a new object from them too. Maybe I am not doing it properly.

![screen](https://user-images.githubusercontent.com/52150408/133769538-118e73a3-8769-4813-95fa-f91bec0a76c3.png)

**Comment by rohitdavas** [comment]
Ok. I got you. You are saying 

1. Remove the unnessary bones.
2. Go to edit mode and remove the vertices that we don't need.

**Comment by kaiidams** [comment]
Yes, you can remove unneeded vertices in the mesh in the edit mode.

**Comment by rohitdavas** [comment]
Thanks. It helped.
